/*Set Database*/

USE potholes;

DROP TABLE IF EXISTS workorders;
DROP TABLE IF EXISTS reported;
DROP TABLE IF EXISTS priority;
DROP TABLE IF EXISTS reporter;
DROP TABLE IF EXISTS location;
DROP TABLE IF EXISTS status;
DROP TABLE IF EXISTS zone;

