openapi: 3.0.1
info:
  description: KnoxPothole API Documentation
  version: "1.0.0"
  title: KnoxPothole API
servers:
  - url: /api/v1
paths:
  /reports/get:
    get:
      operationId: reports.getAllReports
      tags:
        - Get
        - App
      summary: Reports Get
      responses:
        '200':
          description: Successfully received list of reports
          content:
            application/json:
              schema:
                title: Array of Reports
                type: array
                items:
                  properties:
                    location:
                      type: object
                      description: The location of an object
                    status_id:
                      type: integer
                      description: The status of pothole filling
                    zone:
                      type: string
                      description: Zone of pothole location
                    priority:
                      type: string
                      description: The priority
  /reports/post:
    post:
      operationId: reports.postReport
      tags:
        - Post
        - App
      summary: Add new report
      description: Add new report
      responses:
        '201':
          description: Successfully added a report
      requestBody:
        description: Add new report
        required: true
        content:
          application/json:
            schema:
              required:
                - location
                - status_id
                - zone
              type: object
              properties:
                location:
                  type: object
                  description: The location of an object
                status_id:
                  type: integer
                  description: The status of pothole filling
                zone:
                  type: string
                  description: Zone of pothole location
                priority:
                  type: string
                  description: The priority
