openapi: 3.0.1
info:
  description: KnoxPothole API Documentation
  version: "1.0.0"
  title: KnoxPothole API
servers:
  - url: /api/v1
paths:
  /reports/get:
  get:
    operationId: reports.get
    summary: Get a list of reports
    description: Get a list of reports
    reponses:
    '200':
      description: Succesfully recieved the list of reports
      content:
      application/json:
        schema:
        title: All Reports
        type: array
        items:
          properties:
          location:
            type: object
            description: Location of the pothole
          status_id:
            type: int
            description: Status of the pothole filling
          zone:
            type: string
            description: Zone of the pothole location
          reporter:
            type: string
            description: Name of the person or group that reported the pothole
          priority:
            type: string
            description: Priority
 /reports/post:
  post:
    operationid: reports.post
    summary: asdf
    description: asdf
    responses:
      '201':
        description: Added a report
    requestBody:
      description: Add report
      required: true
      content:
        application/json:
        schema:
          required:
          - location
          - status_id
          - zone
          type: object
          properties:
          location:
            type: object
            description: Location
          status_id:
            type: int
            description: Status
          zone:
            type: string
            description: Zone
          reporter:
            type: string
            description: Reporter Name
          priority:
            type: string
            description: Priority

